services:
  freeline-db:
    image: postgres:18.3-alpine
    container_name: freeline-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - freeline-db-data:/var/lib/postgresql/data
    networks:
      - infra-public
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  freeline-redis:
    image: redis:8.6.1-alpine
    container_name: freeline-redis
    restart: always
    environment:
      TZ: Asia/Seoul
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - freeline-redis-data:/data
    networks:
      - infra-public
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  freeline-rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: freeline-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VIRTUAL_HOST}
      TZ: Asia/Seoul
    volumes:
      - freeline-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - infra-public
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  freeline-backend:
    image: freeline-backend:latest
    container_name: freeline-backend
    restart: always
    depends_on:
      freeline-db:
        condition: service_healthy
      freeline-redis:
        condition: service_healthy
      freeline-rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      DB_HOST: freeline-db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: freeline-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      RABBITMQ_HOST: freeline-rabbitmq
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VIRTUAL_HOST: ${RABBITMQ_VIRTUAL_HOST}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
      ENCRYPTION_SECRET_KEY: ${ENCRYPTION_SECRET_KEY}

      CLOUDFLARE_ACCESS_KEY: ${CLOUDFLARE_ACCESS_KEY}
      CLOUDFLARE_BUCKET: ${CLOUDFLARE_BUCKET}
      CLOUDFLARE_ENDPOINT: ${CLOUDFLARE_ENDPOINT}
      CLOUDFLARE_OUTER_PREFIX: ${CLOUDFLARE_OUTER_PREFIX}
      CLOUDFLARE_SECRET_KEY: ${CLOUDFLARE_SECRET_KEY}
      
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_SERVICE_ACCOUNT_BASE64: ${FIREBASE_SERVICE_ACCOUNT_BASE64}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    networks:
      - infra-public

volumes:
  freeline-db-data:
  freeline-redis-data:
  freeline-rabbitmq-data:


networks:
  infra-public:
    external: true
