services:
  backend:
    container_name: infisical-backend
    image: infisical/infisical:v0.158.7
    restart: unless-stopped
    pull_policy: always
    env_file: .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - infra-public
      - infisical-internal

  redis:
    image: redis:8.6.1-alpine
    container_name: infisical-dev-redis
    env_file: .env
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Seoul
    networks:
      - infisical-internal
    volumes:
      - redis_data:/data

  db:
    container_name: infisical-db
    image: postgres:14-alpine
    restart: always
    env_file: .env
    environment:
      - TZ=Asia/Seoul
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - infisical-internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
  redis_data:


networks:
  infra-public:
    external: true
  infisical-internal:
    driver: bridge
