spring:
  jpa:
    defer-datasource-initialization: true
  # local 또는 live 활성화
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  # 파일 업로드 공통 설정
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

# JWT 및 암호화 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}

# Swagger UI
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
    groups-order: asc
    tags-sorter: alpha
    disable-swagger-default-url: true
    try-it-out-enabled: true