spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:freeline}
    username: ${DB_USERNAME:freeline}
    password: ${DB_PASSWORD:freeline}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "SET TIME ZONE 'Asia/Seoul'"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:0000}
  mail:
    host: smtp.gmail.com
    port: 587
    username: a207.freeline@gmail.com
    password: bvgp xqck ttow poiq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:your_local_secret_key_for_freeline_min_32_chars}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600000}

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY:local_encryption_key_16_chars}
